const KEY='elderlyCareCompanion_v1';
const today=()=>new Date().toDateString();
const defaultState={user:null,name:'',day:today(),water:0,feeling:'',family:{name:'',phone:''},medicines:[{id:1,name:'BP Tablet',dose:'1 tablet',time:'08:00',taken:false},{id:2,name:'Vitamin D',dose:'1 capsule',time:'13:00',taken:false}],sosLog:[]};
let state=load();
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s){s.day!==today()&&(s.day=today(),s.water=0,s.feeling='',s.medicines.forEach(m=>m.taken=false),s.sosLog=[]);return {...defaultState,...s}}}catch(e){}return structuredClone(defaultState)}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function showView(v){$$('.view').forEach(x=>x.classList.remove('active-view'));$('#'+v+'View').classList.add('active-view');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));render()}
function sorted(){return [...state.medicines].sort((a,b)=>a.time.localeCompare(b.time))}
function time12(t){let [h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h<12?'AM':'PM'}`}
function render(){const meds=sorted(),taken=meds.filter(m=>m.taken).length;$('#greeting').textContent=`Good ${new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}`;$('#userGreeting').textContent=state.name?`Hello, ${state.name}. Here is your care summary for today.`:'Here is your care summary for today.';$('#statMeds').textContent=`${taken}/${meds.length}`;$('#statWater').textContent=`${state.water}/8`;$('#statFeeling').textContent=state.feeling||'—';$('#waterText').textContent=`${state.water} of 8 glasses`;
const next=meds.find(m=>!m.taken);$('#insightText').textContent=meds.length?`You have taken ${taken} of ${meds.length} medicines today. ${next?`Next: ${next.name} at ${time12(next.time)}.`:'All medicines are done. Well done!'} Water: ${state.water} of 8 glasses.`:`Add medicine reminders to get started. Water: ${state.water} of 8 glasses.`;$('#medicineProgress').textContent=meds.length?`${taken} of ${meds.length} taken`:'No reminders yet';$('#medicineBar').style.width=meds.length?`${taken/meds.length*100}%`:'0%';$('#todayMedicineList').innerHTML=meds.map(m=>medicineHTML(m,false)).join('')||'<p class="muted">No medicines added.</p>';$('#allMedicineList').innerHTML=meds.map(m=>medicineHTML(m,true)).join('')||'<p class="muted">Nothing saved yet.</p>';$('#feelingMessage').textContent=state.feeling==='Good'?'Glad you are feeling good!':state.feeling==='Okay'?'Take it easy and stay hydrated.':state.feeling==='Not well'?'If symptoms are serious, use SOS or call 112.':'';$('#familyName').value=state.family.name;$('#familyPhone').value=state.family.phone;renderAlerts()}
function medicineHTML(m,del){return `<div class="medicine-row"><div class="medicine-info"><strong>${escapeHTML(m.name)}</strong><span>${escapeHTML(m.dose)} · ${time12(m.time)}</span></div>${del?`<button class="secondary small-btn" data-delete="${m.id}">Delete</button>`:m.taken?'<strong class="success">✓ Taken</strong>':`<button class="good small-btn" data-take="${m.id}">Taken</button>`}</div>`}
function escapeHTML(x){const d=document.createElement('div');d.textContent=x;return d.innerHTML}
function renderAlerts(){const now=new Date().toTimeString().slice(0,5), items=[];state.medicines.forEach(m=>{if(!m.taken&&m.time<now)items.push(`Missed medicine: ${m.name} was due at ${time12(m.time)}.`)});state.sosLog.forEach(x=>items.push(x));const list=$('#alertsList');list.innerHTML=items.length?items.map(x=>`<div class="card alert-card"><strong>⚠ Alert</strong><p>${escapeHTML(x)}</p></div>`).join(''):'<div class="card">No alerts. All good!</div>';$('#alertBadge').textContent=items.length;$('#alertBadge').classList.toggle('hidden',!items.length)}
function loginMode(register){$('#nameField').classList.toggle('hidden',!register);$('#authBtn').textContent=register?'Register':'Login';$$('.tab').forEach(t=>t.classList.toggle('active',(t.dataset.auth==='register')===register));$('#authError').textContent=''}
$$('[data-auth]').forEach(b=>b.onclick=()=>loginMode(b.dataset.auth==='register'));
$('#authBtn').onclick=()=>{const phone=$('#phoneInput').value.replace(/\s/g,''),pin=$('#pinInput').value,name=$('#nameInput').value.trim(),register=$('#authBtn').textContent==='Register';if(!/^\d{10}$/.test(phone))return $('#authError').textContent='Enter a valid 10-digit mobile number.';if(!/^\d{4}$/.test(pin))return $('#authError').textContent='PIN must contain 4 digits.';if(register&&!name)return $('#authError').textContent='Please enter your name.';state.user=phone;state.name=name||state.name;save();$('#authScreen').classList.add('hidden');$('#appScreen').classList.remove('hidden');render()};
$('#googleBtn').onclick=()=>alert('Google sign-in is not connected in this demo.');$('#logoutBtn').onclick=()=>{state.user=null;save();$('#appScreen').classList.add('hidden');$('#authScreen').classList.remove('hidden')};
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$$('[data-feeling]').forEach(b=>b.onclick=()=>{state.feeling=b.dataset.feeling;save();render();if(state.feeling==='Not well')showView('chat')});
$('#waterPlus').onclick=()=>{state.water=Math.min(8,state.water+1);save();render()};$('#waterMinus').onclick=()=>{state.water=Math.max(0,state.water-1);save();render()};
$('#addMedicine').onclick=()=>{const name=$('#medicineName').value.trim(),dose=$('#medicineDose').value.trim(),time=$('#medicineTime').value;if(!name||!dose||!time)return $('#medicineMsg').textContent='Please fill all medicine fields.';state.medicines.push({id:Date.now(),name,dose,time,taken:false});save();$('#medicineName').value=$('#medicineDose').value=$('#medicineTime').value='';$('#medicineMsg').textContent='✓ Reminder saved successfully.';render();setTimeout(()=>$('#medicineMsg').textContent='',1800)};
document.addEventListener('click',e=>{const take=e.target.closest('[data-take]'),del=e.target.closest('[data-delete]');if(take){state.medicines.forEach(m=>{if(String(m.id)===take.dataset.take)m.taken=true});save();render()}if(del){state.medicines=state.medicines.filter(m=>String(m.id)!==del.dataset.delete);save();render()}});
function assistant(q){const l=q.toLowerCase(),next=sorted().find(m=>!m.taken);if(/medic|tablet|pill|next/.test(l))return next?`Your next medicine is ${next.name}, ${next.dose}, at ${time12(next.time)}.`:'You have taken all your medicines today. Well done!';if(/water|drink|hydrat/.test(l))return `Try to stay hydrated. You have had ${state.water} of 8 glasses today, unless your doctor has advised a different amount.`;if(/sleep/.test(l))return'Keep a regular sleep time, reduce screen use before bed, and keep the room comfortable and quiet.';if(/eat|food|diet/.test(l))return'Choose balanced meals with vegetables, fruit, whole grains and a suitable protein source. Follow any diet advice given by your doctor.';if(/pain|knee/.test(l))return'For mild pain, rest the affected area and avoid activities that make it worse. If pain is severe, sudden or persistent, speak with a doctor.';if(/dizz|faint|breath|chest pain|stroke|bleed/.test(l))return'This may need urgent attention. Please press SOS or call 112 now.';return'I can help with general questions about medicines, hydration, food, sleep, exercise and wellbeing. For a medical diagnosis, please speak with a doctor.'}
function sendQuestion(q){q=q.trim();if(!q)return;addBubble(q,'me');setTimeout(()=>addBubble(assistant(q),'bot'),350)}function addBubble(t,c){const d=document.createElement('div');d.className=`bubble ${c}`;d.textContent=t;$('#chatLog').appendChild(d);$('#chatLog').scrollTop=$('#chatLog').scrollHeight}
$('#sendChat').onclick=()=>{const q=$('#chatInput').value;$('#chatInput').value='';sendQuestion(q)};$('#chatInput').onkeydown=e=>{if(e.key==='Enter')$('#sendChat').click()};$$('[data-question]').forEach(b=>b.onclick=()=>sendQuestion(b.dataset.question));
$('#saveFamily').onclick=()=>{const phone=$('#familyPhone').value.replace(/\s/g,''),name=$('#familyName').value.trim();if(!/^\d{10}$/.test(phone))return $('#familyMsg').textContent='Enter a valid 10-digit number.';state.family={name,phone};save();$('#familyMsg').textContent='✓ Family contact saved.';setTimeout(()=>$('#familyMsg').textContent='',1800)};
$('#sosButton').onclick=()=>{state.sosLog.push(`SOS demo sent at ${new Date().toLocaleTimeString()}. Family contact: ${state.family.name||'not saved'}.`);save();$('#sosStatus').textContent='✓ Emergency alert simulated. In a real emergency, call 112.';renderAlerts()};
if(state.user){$('#authScreen').classList.add('hidden');$('#appScreen').classList.remove('hidden')}render();
setInterval(renderAlerts,30000);
